root: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  no-console: off
  curly:
    - error
    - multi-or-nest
    - consistent
  eqeqeq: warn
  no-throw-literal: warn
  quotes:
    - error
    - double
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/semi": warn
  indent:
    - error
    - 2
    - SwitchCase: 1
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
ignorePatterns: ["out", "dist", "**/*.d.ts"]

